src/objects/Doc2File_Log__c.object
<CustomObject>
    <description>Represents results from converting Document Folders to Content Libraries. Records are created and updated by Apex batch jobs.</description>
    <label>Doc2File Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Doc2File Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Doc2File_Request__c.object
<CustomObject>
    <description>Represents metadata, permissions, and cross-references for converting Document Folders to Content Libraries. Records are created and updated by Apex batch jobs.</description>
    <fields>
        <fullName>Folder_Developer_Name__c</fullName>
        <description>Developer Name of the original Document Folder. By storing this data, we avoid extra code and SOQL queries in the batch jobs.</description>
        <inlineHelpText>Developer Name of the original Document Folder.</inlineHelpText>
        <label>Folder Developer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Document Folder ID to convert to Content Library.</description>
        <externalId>true</externalId>
        <inlineHelpText>Document Folder ID to convert to Content Library.</inlineHelpText>
        <label>Folder ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Folder_Name__c</fullName>
        <description>Name of the original Document Folder. By storing this data, we avoid extra code and SOQL queries in the batch jobs.</description>
        <inlineHelpText>Name of the original Document Folder.</inlineHelpText>
        <label>Folder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_IDs__c</fullName>
        <description>Comma-delimited list of Group IDs derived from the DocumentFolder sharedTo entries from Metadata API. https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_folder.htm</description>
        <inlineHelpText>Comma-delimited list of Group IDs derived from the DocumentFolder sharedTo entries from Metadata API.</inlineHelpText>
        <label>Group IDs</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Library_ID__c</fullName>
        <description>The new Content Library created to replace the Document Folder. Populated by batch apex jobs.</description>
        <inlineHelpText>The new Content Library created to replace the Document Folder.</inlineHelpText>
        <label>Library ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Library_Permission_ID__c</fullName>
        <description>The content library permission to grant to members of the new library. In Setup menu in Classic UI, find &quot;Content Permissions&quot;. Learn more about content library management at https://help.salesforce.com/articleView?id=collab_files_library_folders.htm</description>
        <inlineHelpText>The content library permission to grant to members of the new library.</inlineHelpText>
        <label>Library Permission ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Library_Public_Group_ID__c</fullName>
        <description>Content Libraries can be shared to users and public groups, but Document Folders can be shared to users, public groups, and roles. To bridge the gap, then a public group per library is created and the library shared with the new group. All members that the Document Folder was shared with are added as members of the new library public group. Populated by batch apex job.</description>
        <inlineHelpText>Public Group that represents who the original Document Folder was shared to. This defines the new Library&apos;s membership.</inlineHelpText>
        <label>Library Public Group ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Doc2File Request</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Doc2File Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Doc2File_CreateLibrariesBatchable.cls
/**
 * Author: Doug Ayers
 * Website: https://douglascayers.com
 * GitHub: https://github.com/douglascayers/sfdc-convert-documents-to-files
 * License: BSD 3-Clause License
 */
public without sharing class Doc2File_CreateLibrariesBatchable implements Database.Batchable<SObject> {

    public Database.QueryLocator start( Database.BatchableContext context ) {

        System.debug( 'Doc2File_CreateLibrariesBatchable.start: ' + context );

        return Database.getQueryLocator([
            SELECT
                Id,
                Folder_ID__c,
                Folder_Name__c,
                Folder_Developer_Name__c,
                Group_IDs__c,
                Library_ID__c,
                Library_Public_Group_ID__c,
                Library_Permission_ID__c
            FROM
                Doc2File_Request__c
            WHERE
                Library_ID__c = null
            ORDER BY
                Folder_Name__c,
                Folder_ID__c
        ]);
    }

    public void execute( Database.BatchableContext context, List<Doc2File_Request__c> records ) {

        System.debug( 'Doc2File_CreateLibrariesBatchable.execute: ' + context );

        SavePoint sp = Database.setSavepoint();

        try {

            Doc2File_FolderConversionService service = new Doc2File_FolderConversionService();

            service.createLibrariesForDocumentFolders( records );

        } catch ( Exception e ) {

            Database.rollback( sp );

            System.debug( LoggingLevel.ERROR, e );

            // todo create doc2file_log__c

        }

    }

    public void finish( Database.BatchableContext context ) {

        System.debug( 'Doc2File_CreateLibrariesBatchable.finish: ' + context );

        // todo send progress update email to user that libraries created, now starting document conversion job

        Database.executeBatch( new Doc2File_ConvertDocsToFilesBatchable() );

    }

}
/*
BSD 3-Clause License

Copyright (c) 2018, Doug Ayers, douglascayers.com
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/